language: node_js

before_install:
  - gem install sass
  - gem install compass
  - gem install coveralls

node_js:
  - "0.10"

services: mongodb

install: 
  - npm install
  - npm install -g grunt-cli
  
script: 
    -grunt all # Run the tests
    -npm run coveralls # Upload coverage
