language: node_js

before_install:
  - gem install coveralls

node_js:
  - "0.10"

services: mongodb

install: 
  - npm install
  - npm install -g gulp

script: 
    - gulp test # Run linting, compliation and tests
    - npm run coveralls # Upload coverage
