language: node_js
node_js:
  - "0.10"
  - "0.8"

services: mongodb

install: 
  - npm install
  - npm install -g grunt-cli
before_script: 
  - grunt lint # Check for style violations
  - NODE_ENV=travis-ci npm start &
  - sleep 10   # Give it some time to warm up 
  
script: grunt test # Run the tests
