language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

services: mongodb

install: 
  - npm install
  - npm install -g grunt-cli
before_script: 
  - grunt
  - NODE_ENV=travis-ci npm start &
  - sleep 10 # Give it some time to warm up 
script: npm test
