
---
#
#    unity-profiles config file
#

default: # The default config profile. (With documentation)

    # The port that the API listens for requests on
    listen_port:            80

    # The locale that application will run with (eg. en-US)
    locale:                 "en-US"

    # How much work it takes to hash the passwords stored in the database.
    # For testing and development you can set it to something low but in production you
    # would want to set it to a value that makes it as hard a possible for someone to crack
    # whilst maintaining server performance.
    salt_work_factor:       8

    # The mongodb connection string
    mongo_url:              "mongodb://localhost/unity-profiles"

    # Enable/disable special API extenstions used to make testing easier such as resetting state.
    # Although these test extensions should be designed to only effect test data it is strongly
    # recommended that they be disabled for live environments. (At least until they are protected)
    enable_test_exts:       false

    # Show line number and other information when an error occurs
    show_friendly_errors:   false

    # Maximum records that can be returned by an rest API query
    max_records_per_query:  20

    # How many characters to generate for the code sent to the user when they forget their password
    tempPasswordCodeLength: 8

    # Number of seconds after device activity until it is automatically disconnected.
    device_Timeout_Seconds: 300

    # The settings so that emails can be sent for things such as lost password.
    # Set enabled to false to avoid errors due to incorrect settings.
    # When fake_smtp is set to true, an SMTP server is started by the server
    # to test the sending of emails. This should be set to false in production.
    email_settings:     
        enabled:    false    
        user:       "testUser"
        password:   "testPassword"
        host:       "localhost"
        port:       3001
        ssl:        false
        from:       "forgotpassword@unity-profiles.test"
        fake_smtp:  false

    # Settings to do with code generation (less/browserify etc.) and minification
    code_generation:
        browserify:
            debug: true



development: # The development config profile.
    listen_port:            3000
    locale:                 "en-US"
    salt_work_factor:       3
    mongo_url:              "mongodb://localhost/unity-profiles-dev"
    enable_test_exts:       true
    show_friendly_errors:   true
    max_records_per_query:  20
    tempPasswordCodeLength: 8
    device_Timeout_Seconds: 300
    email_settings: 
        enabled:    true    
        user:       "testUser"
        password:   "testPassword"
        host:       "localhost"
        port:       3001
        ssl:        false
        from:       "forgotpassword@unity-profiles.test"
        fake_smtp:  true
    code_generation:
        browserify:
            debug: true

travis-ci: # The development config profile.
    listen_port:            3000
    locale:                 "en-US"
    salt_work_factor:       1 # Reduce the work factor even more for slower VMs
    mongo_url:              "mongodb://localhost/unity-profiles-dev"
    enable_test_exts:       true 
    show_friendly_errors :  true
    max_records_per_query:  20
    tempPasswordCodeLength: 8
    device_Timeout_Seconds: 300
    email_settings:
        enabled:    true    
        user:       "testUser"
        password:   "testPassword"
        host:       "localhost"
        port:       3001
        ssl:        false
        from:       "forgotpassword@unity-profiles.test"
        fake_smtp:  true
    code_generation:
        browserify:
            debug: true

# TODO: Enable a real email client
heroku:
    listen_port:            5000
    locale:                 "en-US"
    salt_work_factor:       1 # Reduce the work factor even more for slower VMs
    mongo_url:              "mongodb://moussaka:moussaka@ds039960.mongolab.com:39960/moussaka"
    enable_test_exts:       true 
    show_friendly_errors :  true
    max_records_per_query:  20
    tempPasswordCodeLength: 8
    device_Timeout_Seconds: 300
    email_settings:
        enabled:    true    
        user:       "testUser"
        password:   "testPassword"
        host:       "localhost"
        port:       3001
        ssl:        false
        from:       "forgotpassword@unity-profiles.test"
        fake_smtp:  true
    code_generation:
        browserify:
            debug: true
